### PR TITLE
Update to 0.0.6

### PR DESCRIPTION
**Pull request by rmader**
While on it update the runtime and Gstreamer as well.

---

Supersedes https://github.com/flathub/org.sigxcpu.Livi/pull/5

### CODE REVIEW

**Comment by agx** [comment]
Thanks!

**Comment by rmader** [comment]
FTR.: at least on my rk3399 test device the vp9 hw decoder errors out, but for h264 things work fine (and hw decoding is used). Testing the same locally with gst 1.24 / main works fine, so that can hopefully be fixed by just updating the dependencies again in a couple of month.

**Comment by agx** [comment]
Maybe we should disable vp9 stateless in that case (it's broken on im8 as well (h264 and vp8 works))?

**Comment by rmader** [comment]
Yeah, let's do that till the gst 1.24 update. Opened https://github.com/flathub/org.sigxcpu.Livi/pull/7

**Pull request merged**
