### PR TITLE
Update to 0.2.0 and bump Gstreamer to 1.24.4

### PR DESCRIPTION
**Pull request by rmader**
The later notably includes
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/6645
which is important for VP9 or H265 playback on the Librem5 and other
devices.

### CODE REVIEW

**Comment by agx** [comment]
Thanks. Should we combine that with https://gitlab.gnome.org/guidog/livi/-/merge_requests/53 which I could release tomorrow?

**Comment by rmader** [comment]
Yep, that sounds great!

**Comment by agx** [comment]
[Released](https://gitlab.gnome.org/guidog/livi/-/releases/v0.2.0) now. If we stick to the built in sink the dependencies should remain unchanged.

**Comment by rmader** [comment]
> If we stick to the built in sink the dependencies should remain unchanged.

Yeah, I'd say let's stick to it for now to get the update out and switch over later.

**Comment by agx** [comment]
Thanks!

**Pull request merged**
